### ISSUE TITLE
Mouser or Digikey saved basket for BOM?

### ISSUE THREAD

**Issue by crozone** [calcpsu/cphp82001#10]
I'm currently building out the mouser shopping card for the v5 BOM and getting some choice paralysis on the generic parts.

Do you happen to have an existing saved basket for mouser or digikey? If not, should I build one out and submit it for future use?

**Comment by ecsfang** [comment]
That would be a good idea!
The current BOM is not updated (which I realized when mounting my devices not checking it twice before ordering the components ;)).
In short, D4 (1N4148W) is missing from the BOM and R5, R4 and C3 are not needed (as well as U2 as mentioned in the README).

**Comment by grob6000** [comment]
Hi there! BOM has been refereshed with e6dfacf37bfa06bdd88ff2dee844c53cb2cf4b45, apologies for the confusion.

Happy to receive a link for a successful cart, otherwise I'll likely clean up my last Digikey BOM and provide a link in the readme.

**Comment by grob6000** [comment]
Digikey shared list here: https://www.digikey.com.au/en/mylists/list/Z6K09H5IB0

**Comment by crozone** [comment]
Thanks, this is a massive help! I'm currently working on a Mouser version as well. There's a few substitutions that I'll need to double check.
