### ISSUE TITLE
USB connector difficult to solder

### ISSUE THREAD

**Issue by grob6000** [calcpsu/cphp82001#2]
Ground plane connection to USB connector is too strong; challenging to solder without excessive heating of board/plane.
Improve thermal relief for ground pin and shield.

**Comment by MilovdZee** [comment]
Almost not possible to solder with an iron but went fine with my hot air station

**Comment by grob6000** [comment]
Thanks for the feedback. I have adjusted the thermal relief of the USB in v4 - adjacent shield connections are thermally relieved from ground plane, and GND pin I've changed to a single connect. I'd argue micro usb connectors are always a bear to hand solder, but happy to improve AFAIRP. See 2951f1485d85d3fa7d55ea8e0cb5fbce0e2f9556
