### ISSUE TITLE
R1 and R8 values differ between schematics and BOM

### ISSUE THREAD

**Issue by MilovdZee** [calcpsu/cphp82001#4]
It does not really matter but it is just inconsistent.

Also from the specs: Programs the Fast-charge current setting. External resistor from ISET to VSS defines fast charge
current value. Range is 10.8kΩ (50mA) to 675Ω (800mA).

So the 11k resister exceeds the max value. The BOM value of 10k is probably better.

I think you mean to set the values in the schematics also to 1k3 and 10k. That at least is consistent with the specs and the BOM.

**Comment by grob6000** [comment]
The BOM was outdated; I've re-run direct from KICAD and it should now match the v4 schematic (0dc3c41eb4f7892238718d715c050627dc70e223). Thanks for spotting.

R1=1.8k provides USB charging current of 540/1.8 = 300mA, which is an ideal safe charge current of 0.2C for a 1500mAh battery
R1=1.3k would be 415mA, which is close to 0.2C for a 2000mAh battery.

R1+R8 sets the charge current when connected to the HP original charger (in-system). This is more the critical value. I know the datasheet says 10.8k max (50mA min), but hear me out:

The original HP charger supplies 50mA constant current (mine does 49.5mA pretty consistently, I'd be keen to collect more data but given the simple 2 transistor design I'm surprised it's better than +/-2mA).

When the 50mA supply is fed to the pads, the voltage will rise to above B+, and U3 will switch off, preventing this from directly feeding B+ - great. Note that U7 (NCP380) does not prevent backfeed (acts like a diode), so when the pad voltage exceeds 4.4V, U4 will switch on, and connect the pads to VIN of the U1 (BQ21040) via Q2 and U7 (which might be bypassed, if using the regulated design). U1 then starts up and charges the battery at ISET.

* If the total current consumed exceeds what the supply provides (>50mA), then the supply voltage will drop. While U1 will throttle current if the voltage drops below 4.3V (can maintain down at least as far as 3.5V), U4 will switch off at VOUTF=4.4V; prior to any throttling occurring. U4 has a 240ms reset timer, so the effect is a 240ms oscillation (flashing red CHG light). With U7 present, the ~0.3V body diode drop will help a little, so this will be worse in a regulated version.
* If the total current consumed is less than the supply current (<50mA), then the charging works as normal, and the input voltage is regulated by the 5.6V zener.

I did consider relying on the BQ20140 current throttling (i.e. by replacing Q2 with a diode), however this means the charging IC is powered even when the battery is idle. In this case, it will not meet the power good threshold, and stay in standby mode. However, standby current is 125uA. In comparison, U4 consumes 30uA only. The 4.4V threshold must be above the charging output voltage (4.28V max).

Therefore, it's kind of critical that ISET is low enough that the total current draw (ISET + 1mA for U1, 1mA for CHG LED) does not exceed the constant current input supply (maybe 48mA minimum), such that a small margin is available to run through the 5.6V zener and maintain the pad voltage >4.4V. Using the table below, even 12.8k is marginal (<46mA being the target):

| R1 | R8 | R1+R8 | ISET <br> MIN <br> KISET=470 | ISET<br>Nominal<br>KISET=527 | ISET<br>Max<br>KISET=605 | Recommend? |
| -- | -- | -- | -- | -- | -- | -- |
| 1.8k | 10k | 11.8k | 🟢 39.8mA | 🟢 44.7mA | 🔴  51.3mA |  |
| 1.8k | 11k | 12.8k | 🟢 36.7mA | 🟢 41.2mA | 🟠 47.3mA | ✔️|
| 1.3k | 10k | 11.3k | 🟢 41.6mA | 🟠 46.6mA | 🔴 53.5mA | |
| 1.3k | 11k | 12.3k | 🟢 38.2mA | 🟢 42.8mA | 🟠 49.2mA | ✔️ |

Note the datasheet does provide KISET values for 25~60mA (and lower!):
![image](https://github.com/user-attachments/assets/1eafd8ec-a903-44fc-a34a-023d7be9b040)

Now you've made me look at it again, I could in theory put 1V of diode between Q2 pin 3 and VCC, such that the idle voltage of 5.6V meant 4.6V at VCC (plenty for a 50mA charge), and at the cutout of VOUTF=4.4V, VCC was 3.4V - which would let U1 current throttle as designed, and thus the ISET could be 50mA (so 9.1k would work), and charge would be 20% faster.

**Comment by MilovdZee** [comment]
Wow, a very comprehensive answer :) I'll study it :)

**Comment by grob6000** [comment]
R1 and R8 values revisited for v5: 30ffbc13f589585e5461ab38b471176c49de2603
